apiVersion: v1
kind: Namespace
metadata:
  name: express-app
  labels:
    name: express-app
    purpose: learning
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: express-sa
  namespace: express-app
  labels:
    app: express
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: express-read-config
  namespace: express-app
  labels:
    app: express
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: express-read-config-bind
  namespace: express-app
  labels:
    app: express
subjects:
- kind: ServiceAccount
  name: express-sa
  namespace: express-app
roleRef:
  kind: Role
  name: express-read-config
  apiGroup: rbac.authorization.k8s.io 